### ISSUE TITLE
I would like to know more about how to use it.

### ISSUE THREAD

**Issue by daeinlee** [DoranekoSystems/frida-ceserver#20]
"Hello. Thank you for creating this excellent tool.
Is it correct to run frida-ceserver using a command like "python main.py -p 12857"?
Also, is the correct method to run the ceserver distributed by Cheat Engine, then use "adb forward tcp:52736 tcp:52736", and access it through Cheat Engine via network?
If running with "python main.py -p 12857" is correct, I'm encountering the following error. Is it possible to attach using options like spawn?

`Traceback (most recent call last):
File "C:\Users\daeinlee\frida-ceserver-main\main.py", line 202, in <module>
main(args[1])
File "C:\Users\daeinlee\frida-ceserver-main\main.py", line 106, in main
session = device.attach(app_name) `

Additionally, it would be great if the project could include a user-friendly guide for beginners.
I would appreciate detailed instructions on how to use this tool."

**Comment by DoranekoSystems** [comment]
Sorry for the lack of clarity.
I have updated the config and README.
