### ISSUE TITLE
No module named 'frida'

### ISSUE THREAD

**Issue by fsleo** [DoranekoSystems/frida-ceserver#24]
How to install Frida in iOS, I tried adding it https://build.frida.re Then install Frida, but it is actually frida-server
When I run python main. py, it prompts:
./frida-ceserver/main.py", line 8, in <module>
import frida
ModuleNotFoundError: No module named 'frida'
thank you

**Comment by DoranekoSystems** [comment]
Thank you for your comment.  
Requires installation of the relevant python libraries.
`pip install -r requirements.txt`

**Comment by fsleo** [comment]
Thank you for your reply. As stated in the document:
Install frida on iOS.

python main.py Cydia
# or
python main.py com.saurik.Cydia
# or
python main.py -p ProcessId
# or
: config.toml mode = "enum"
python main.py

When I am executing Python main. py, it prompts: No module named 'frida', I don't know what to do, I tried installing Python 3.9 on iOS, python3 -m pip install frida, However, it did indeed fail

**Comment by DoranekoSystems** [comment]
python runs on Host OS (Mac or Windows).
pip install is also performed on the Host OS.

**Comment by fsleo** [comment]
iPad:/usr/bin root# ./ceserver_mini
CEServer. Waiting for client connection
Listening success
﻿
iPad:/usr/bin root# ./debugserver 0.0.0.0:1236
debugserver-300.2 for arm64.
Listening to port 1236 for a connection from 0.0.0.0...
﻿
mac:
python main.py
﻿
﻿
<img width="294" alt="image" src="https://github.com/user-attachments/assets/d17e73f3-1c1c-4221-9fab-5c89812ed523" />
﻿
accept ('127.0.0.1', 64829)
EXCEPTION:3
Traceback (most recent call last):
  File "/Users/zlh/Downloads/ios-ce/frida-ceserver/ceserver.py", line 1302, in main_thread
    ret = handler(conn, native_client, command, thread_count)
  File "/Users/zlh/Downloads/ios-ce/frida-ceserver/ceserver.py", line 622, in handler
    SESSION = DEVICE.attach(pid)
  File "/Users/zlh/Downloads/ios-ce/frida-ceserver/path/to/venv/lib/python3.13/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "/Users/zlh/Downloads/ios-ce/frida-ceserver/path/to/venv/lib/python3.13/site-packages/frida/core.py", line 1071, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.NotSupportedError: need Gadget to attach on jailed iOS; its default location is: /Users/zlh/.cache/frida/gadget-ios.dylib
accept ('127.0.0.1', 64838)

**Comment by fsleo** [comment]
Thank you so much, I have successfully run and used it Thanks again!
